apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluedep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: v1 
  template:
    metadata:
      name: podv1
      labels:
        app: v1 
    spec:
      containers:
      - name: cont1
        image: httpd
        ports:
        - containerPort: 80    
