apiVersion: apps/v1
kind: Deployment
metadata:
  name: greendep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: v2
  template:
    metadata:
      name: podv1
      labels:
        app: v2
    spec:
      containers:
      - name: cont2
        image: nginx
        ports:
        - containerPort: 80 
